### ISSUE TITLE
[EngAut]: Experiment: chatbot

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk-docs#15]
Because why not! See: https://forum.parity.io/t/i-built-a-polkadot-chatgpt-bot-here-are-the-things-i-learned/1798
```[tasklist]
### Tasks
- [x] MVP -> https://github.com/paritytech/chatbot
- [ ] https://github.com/paritytech/chatbot/issues/3
- [ ] https://github.com/paritytech/chatbot/issues/1
- [ ] https://github.com/paritytech/chatbot/issues/13
- [ ] https://github.com/paritytech/chatbot/issues/23
```

**Comment by hummusonrails** [comment]
@kianenigma You can check out the latest update on this that @Bullrich posted in the forum on that thread. It's come a long way!

**Comment by mordamax** [comment]
Since the MVP/Experiment was delivered (https://forum.parity.io/t/i-built-a-polkadot-chatgpt-bot-here-are-the-things-i-learned/1798/24) I'm closing this initial item as completed. Further work is not planned for now, at least by us, but it's open for contributions and adding either more sources or UI changes
