### ISSUE TITLE
Tracking Issue for rust-docs improvements

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk-docs#31]
### FRAME Macros 

For each of these, we should have a macro stub in place (https://paritytech.github.io/polkadot-sdk/master/frame_support/pallet_macros/index.html), and then put the documentation of the macro in the stub. 

All rust-docs should be foundational, use real examples etc.

- [ ] call,call_index, compact, weight,
- [ ] config, constant, disable_frame_system_supertrait_check, extra_constants, no_default, no_default_bounds
- [ ] storage, storage_prefix, storage_version, generate_store, getter, type_value, unbounded, whitelist_storage: https://github.com/paritytech/polkadot-sdk/pull/1714/files
- [ ] pallet::pallet, storage_version, without_storage_info
- [ ] composite_enum
- [ ] genesis_config, build_genesis https://github.com/paritytech/polkadot-sdk/pull/1642/files
- [ ] error
- [ ] event, generate_deposit
- [ ] hooks https://github.com/paritytech/substrate/pull/14578/files
- [ ] import_section, pallet_section
- [ ] inherent
- [ ] origin
- [ ] validate_unsigned

### Types, Traits and Items often used in FRAME 

- [ ] All storage types: https://paritytech.github.io/polkadot-sdk/master/frame_support/storage/types/index.html / https://github.com/paritytech/polkadot-sdk/pull/1714/files
- [ ] `DispatchResult`, `DispatchError`, `DispatchResultWithPostInfo`
- [ ] `trait Hooks` https://github.com/paritytech/substrate/pull/14578/files
- [ ] `trait BuildGenesisConfig`
- [ ] `trait SignedExtension`
- [ ] `trait ValidateUnsigned`
- [ ] literally everything in `frame_system`.

### Types, Traits and Items often used a runtime

Scan a top level runtime, and see which types are often used. Here are some examples, but more can be added. Some groundwork for this is done in https://github.com/paritytech/substrate/pull/14583/files. 

- [ ] `AccountId32`
- [ ] `Multi*`
- [ ] `RuntimeVersion`
- [ ] `UncheckedExtrinsic`

### Umbrella crates and their descendants 

The `developer-hub` will have multiple umbrella crates (see [here](https://github.com/paritytech/polkadot-sdk/tree/kiz-umbrella-crates/developer-hub/src/polkadot_sdk)). These umbrella crates are entry points and contain links to many other crates. 

As an example, `substrate` umbrella crate will link to a bunch of CLI, RPC and consensus related crates. 

We expect users to traverse these links and click on them. Therefore these crates should have great documentation. 

```[tasklist]
### Subtasks
- [ ] https://github.com/paritytech/polkadot-sdk-docs/issues/35
```
