### ISSUE TITLE
Document `#[pallet::xxx]` macros

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk-docs#35]
Document all `#[pallet::xx]` macros. 
Look into the work done for `#[pallet::storage]`, `#[pallet::call]` and  `#[pallet::genesis_xxx]` for example and inspiration. 
```[tasklist]
### Tasks
- [x] `frame_support_procedural::constant_name` fix links
- [x] `frame_support_procedural::constant` fix links
- [x] `frame_support_procedural::crate_to_crate_version` needs docs
- [x] `frame_support_procedural::benchmark` fix link
- [x] `frame_support_procedural::benchmarks` fix link
- [x] `frame_support_procedural::block` fix link
- [x] `frame_support_procedural::call_index` fix docs and link
- [x] Remove "Rust-Analyzer users" prefix from note linking to frame_support docs
- [x] `frame_support_procedural::error` fix links
- [x] `frame_support_procedural::event` fix links
- [x] `frame_support_procedural::extrinsic_call` fix link
- [x] `frame_support_procedural::feeless_if` fix links
- [x] `frame_support_procedural::generate_deposit` fix links
- [x] `frame_support_procedural::genesis_build` fix link
- [x] `frame_support_procedural::genesis_config` fix link
- [x] `frame_support_procedural::hooks` fix links
- [x] `frame_support_procedural::inject_runtime_type` needs docs
- [x] `frame_support_procedural::instance_benchmarks` fix link
- [x] `frame_support_procedural::origin` fix link
- [x] `frame_support_procedural::pallet` fix links
- [x] `frame_support_procedural::require_transactional` needs docs
- [x] `frame_support_procedural::storage` fix link
- [x] `frame_support_procedural::storage_alias` needs doc
- [x] `frame_support_procedural::storage_version` fix links
- [x] `frame_support_procedural::type_value` fix link
- [x] `frame_support_procedural::validate_unsigned` fix links
```

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/decentralized-futures-ecosystem-devrel-team-for-polkadot-by-papermoon/5811/7
