### ISSUE TITLE
Finish up Polkadot document

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk-docs#66]
In docs/sdk/src/polkadot_sdk/polkadot.rs

### TODOs
- [x] link to approval checking article
- [x] weakest link in bridges systems
- [x] add more context and explanations about Polkadot as the Ubiquitous Computer and related tech
